<h1 style="color:#77dc23;text-align:center;">Numpy</h1>

_**Application of numpy**_
- A Powerful N-dimensional Array object
- Sophisticated(broadcsting) function
- Tools for integrating C\C++ and fortan code
- useful linear algebra, fourier transforms and random number capabilities


# Properties and Atrributes
- 1. Shape
- 2. nDim
- 3. Size
- 4. Itemsize
- 5. Dtype
- 6. astype

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
#Two dimension arrary
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4 = np.ones((3,2))
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr6 = np.arange(5,15,2) # 1 starting point 2 and point 3 jumping points
arr6

array([ 5,  7,  9, 11, 13])

In [9]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8 = np.copy(arr7)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr1.shape # shape of array 1

(5,)

In [12]:
arr5.shape

(5, 5)

In [13]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
arr9.ndim # to find dimensions

3

In [15]:
#Number of elements in the array.
arr4.size

6

In [16]:
#Length of one array element in bytes.
print(arr3)
print("Length of array in bytes: ",arr3.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]]
Length of array in bytes:  8


In [17]:
#Length of one array element in bytes.
arr1.itemsize

4

In [22]:
arr13 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
arr12[:,2:4] #slicing column

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [20]:
arr12[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [24]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
